name: BrandonPark.org
favicon: null
layout_spectrum: 0.007315456634387374
typography_spectrum: 0.6873190863989294
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.3436538395471871
  lightness: 0.5836257785558701
  saturation: 0.5505339235533029
  rhythmicContrast: 0.8485057291109115
purpose: []
