purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.550534
  brandStrength: 0.3436538395471871
  lightness: 0.1630824
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  rhythmicContrast: 0.8485057
cta:
  bucket: null
  version: null
  domain: null
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
name: BrandonPark.org
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.2670251
layout_spectrum: 0.453405
